### ISSUE TITLE
K: MapPLUTO

### ISSUE THREAD

**Issue by lseirup** [NYCPlanning/edm-overview#25]

**Comment by AmandaDoyle** [comment]
Successfully ran the development of PLUTO using PTS as the input source.  Started first round of QA/QC

https://github.com/NYCPlanning/db-pluto-qaqc/blob/19v1_baiyue/19v1/pluto19v1-18v2_1-comparison.ipynb

**Explanation of differences** 
**Owner name** went from a to a 21 to an 80 byte field and they removed some NULL values
<img width="1381" alt="Screen Shot 2019-05-30 at 2 35 53 PM" src="https://user-images.githubusercontent.com/5611960/58655799-f53dc380-82e8-11e9-826b-b484cbbd822c.png">

**Land use**,  **sanitdistrict**,  and **tract2010** leading zeros are not maintained in pluto 18v2.1 csv.  Leading zeros are what we want for Land use and tract2010 but sanitdistrict is numeric
<img width="341" alt="Screen Shot 2019-05-30 at 2 47 07 PM" src="https://user-images.githubusercontent.com/5611960/58656204-da1f8380-82e9-11e9-903a-a867dbb1bc6f.png">
<img width="470" alt="Screen Shot 2019-05-30 at 2 49 52 PM" src="https://user-images.githubusercontent.com/5611960/58656612-a002b180-82ea-11e9-80e1-b2493a3610e5.png">

*Extension* 
Added new N value.  Need to see what N means
<img width="235" alt="Screen Shot 2019-05-30 at 2 55 38 PM" src="https://user-images.githubusercontent.com/5611960/58656868-11426480-82eb-11e9-98d7-36dd43a239a4.png">

**CondoNo**
Now have leading numbers before condo number.  Need to correct
<img width="348" alt="Screen Shot 2019-05-30 at 2 57 11 PM" src="https://user-images.githubusercontent.com/5611960/58656963-42229980-82eb-11e9-8c61-a61bbbb90b8f.png">

**Residfar**
1) because in update to souce data
2) because of format of numbers.  Need to correct this
<img width="438" alt="Screen Shot 2019-05-30 at 3 00 21 PM" src="https://user-images.githubusercontent.com/5611960/58657204-c7a64980-82eb-11e9-96ba-9724124e8b51.png">

**Appbbl**
Records that did not have an appbbl now do
<img width="423" alt="Screen Shot 2019-05-30 at 3 02 04 PM" src="https://user-images.githubusercontent.com/5611960/58657308-fb816f00-82eb-11e9-9fda-8790b12f9fe6.png">

**yearalter1**
Error in generating values.  Probably transcends into other related year fields
<img width="403" alt="Screen Shot 2019-05-30 at 3 03 47 PM" src="https://user-images.githubusercontent.com/5611960/58657447-4a2f0900-82ec-11e9-96f1-bd9c0751bc57.png">

**plutomapid**
Lots of records went from 1 to 3.  This may be correct but need to investigate
<img width="413" alt="Screen Shot 2019-05-30 at 3 06 09 PM" src="https://user-images.githubusercontent.com/5611960/58657571-8d897780-82ec-11e9-9637-d1d758a705aa.png">

**Comment by AmandaDoyle** [comment]
Continuing **Appbbl**

It looks like DOF cleaned up their data and values that were `0` are now 'NULL`

<img width="572" alt="Screen Shot 2019-06-05 at 1 23 39 PM" src="https://user-images.githubusercontent.com/5611960/58976609-e1390c80-8795-11e9-88f9-75a304d2aec0.png">

This impacts how `plutomapid` is calculated, because we use the Appbbl.  Need to think about why we use the appbbl and how to correct this
