### ISSUE TITLE
GIS: The Guide - Add section for EDM

### ISSUE THREAD

**Issue by lseirup** [NYCPlanning/edm-overview#52]

**Comment by aferrar** [comment]
Link to the template EDM page currently hosted on ArcGIS Hub:

https://guide-dcp.opendata.arcgis.com/edit?pageId=f678b5ba553546dfbf60ff346d71bb5f

**Comment by aferrar** [comment]
12/18/2019

Need to change the blog on the test edm page to point to the data page on planning digital. Have the link from Lab's API and it returns correct JSON. The problem is I need to host a new site in order to not impact the main page blog item. If I were to alter the PlanningCoordination repo to change to the data section then the main page blog section would receive this change, as well.

1) Need to clone or download PlanningCoordination Guide repo
2) Alter the API link to point to data and publish to new repo under Organization
3) Check to make sure the formatting didn't break (it shouldn't)
4) Host the new repo as a Github Pages page
5) Change section of EDM test page with blog to point to new Github pages link

**Comment by aferrar** [comment]
**12/23/2019**

Cannot currently access the platform. Login credentials have changed. Reached out to Planning Coordination to request new credentials if the old are no longer valid. Cannot work on this issue until this is resolved.

**Comment by croswell81** [comment]
Project is delayed/on-hold until The Guide maintenance/management is worked out with Planning Coordination. Also, need to find a permanent solution for storing the Guide content - should not be open source (github, etc.) but should not have another login (sharepoint, etc.).
