### ISSUE TITLE
Modify PAD Difference File Python Script

### ISSUE THREAD

**Issue by aferrar** [NYCPlanning/edm-overview#712]
GRU script is coded to only accept Friday dates for a variable DTM pull. Need to adjust script to account for variability in pull date. (G EDM GRU DOCS PAD - Docs)

**Comment by croswell81** [comment]
Received confirmation from Jason Black in GR that this is either no longer an issue or the script is no longer needed:

"I think some of the issue was that the script was looking for a Friday date for adding to the name of the DTM or was looking for a Friday date.  I think how we now get the DTM, we might not need to script, or something.  But this might also had something to do with the Arc Map we were creating, and much of the staff wasn’t using the map, so it was no longer needed.  I don’t mind talking it out further though.  I don’t think we have had a problem with doing or getting the DTM. "
