### ISSUE TITLE
Zoning GIS files QA

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#75]
Set up QA procedures for monthly review of TRD Zoning GIS files before they are processed for Bytes/Open Data release.

**Comment by aferrar** [comment]
Steps for QA of Zoning GIS files :

- [ ] Create script to generate and run Topology on desired Zoning features and output a report listing topology errors for each dataset

- [ ] Establish zoning triggers to pull from TRD SDE at agreed upon times so that we do not have to manually reach out to Andrew each month.

**Comment by croswell81** [comment]
Closing: this has been discussed several times. Ultimately TRD would have to set up topology on their SDE and Andrew has indicated that it is not possible. Consider adding repair geometry to Zoning/Sidewalk Cafe tool improvements.
