### ISSUE TITLE
Develop solution for unreconciled versions that will pose an issue for upgrade (TRD)

### ISSUE THREAD

**Issue by jackrosacker** [NYCPlanning/edm-overview#906]

**Comment by jackrosacker** [comment]
Next step: contact Andrew with short term solution and deadline

**Comment by croswell81** [comment]
Email sent to Andrew on 5/9/23:

When we met with you about the upcoming ArcGIS 10.8 upgrade you brought to our attention that there are long-term unreconciled versions on your SDE that preserve snapshots in time of zoning district files. ESRI confirmed that in order to avoid data loss, all unreconciled versions should be posted or deleted before we upgrade. 

The proposed solution is for your team to export those versions to either feature classes with a specific naming convention on the TRD SDE or to a file geodatabase (or both for back-up). Once those versions are exported please delete or post the unreconciled versions. We intend to start testing later this month, so ideally your process would be done by 5/31. If you need more time please let us know.

We will also be reaching out to work with you to develop tests for your data and processes before we fully deploy 10.8 upgrades to the production SDEs.

If you have any questions please reach out the GISTeam.

**Comment by jackrosacker** [comment]
Task completed by Andrew:
![image.png](https://images.zenhubusercontent.com/63c70f3233c7931e09b40a81/c1f5f3ca-7676-47a8-9524-c14980aec749)
Tagging @croswell81 as FYI/confirmation
