### ISSUE TITLE
Housing DB 22q4 processing

### ISSUE THREAD

**Issue by croswell81** [NYCPlanning/edm-overview#923]
Once Housing DB 22q4 scripts are finalized data will need to be processed for open data release:

- [x] **Housing Database [shp/fgdb/csv]**
   - [x] Receive notification from HED/DE that raw data is available
  - [x] Run process, package and distribute scripts
  - [x] Update Open Data log
  - [x] Update Bytes (send email to Webteam)
  - [x] Update AGOL
  - [x] Send email to Open Data team (after confirmation from webteam)
  - [x] Update MMR log

**Comment by caseysmithpgh** [comment]
## 22q4 production steps:

1. Metadata templates were updated to include new fields and field descriptions for this version (meta_templates subfolder of G:/Scripts/dev-housing...)
2. Script 1 was run. This outputs FCs and CSVs to the C:/Temp location.
3. Because CDTA and NTA aggregate FC and CSV outputs had dropped the NTA2020 and CDTA2020 fields, manual steps were taken to rejoin in these fields in from respective LION FCs. 
      - Create copies of the CDTA and NTA FC outputs, open them in arcmap to join them to their respective LION FCs 
      - De-select any unnecessary fields, export FCs with CDTA2020 and NTA2020 fields appended to the end of the schemas
      - Use this [function](http://joshwerts.com/blog/2014/04/17/arcpy-reorder-fields/) to place the FC fields in the desired order, then export 
      - Import the FCs with the corrected schema order back into arcmap and use table to table conversion tool to convert the FCs to CSVs. Because the CSV outputs include OID, ShapeArea, and ShapeLength, they need to undergo further processing with pandas
      - Import the newly exported CSVs as data frames using pandas 
      - use the pd.drop() function to OID, ShapeArea, and ShapeLength fields from both CSVs
      - export the updated CSVs
      - ensure all updated FCs and CSVs have the appropriate schema and use the same naming convention as the script output
4. Replace NTA and CDTA FCs and CSVs in the C:/Temp output location with the corrected versions 
5. Run Script 2 to push to ProdSDE (double check that the metadata reflects updated templates). CDTA and NTA aggregates may require geoprocessing history removal
6. Run Scripts 3 & 4 (public processing)

**Comment by croswell81** [comment]
@caseysmithpgh There were issues with the aggregate tables (unit summary files) outputs for the public. I believe they are all related the year in the file name. Below is a list of items to check when you're back:

CSV, FGDB, shapefiles, 1-zipped files, and 3-unit change summary files folders were missing all aggregate files except CC districts (which is only file w/o a year in file name)


Steps Matt took to fix:
Copy 5 other aggregate files from X:\ITD\casey\devdb_staging\DevDB_22q4_for_review\devDB_22q4.gdb to M:\GIS\BytesProduction\Housing_Dev_DB\2022\22q4\fgdb\housingdb.gdb
--Apply metadata
--clean metadta for path names (path name will not remove)
--Re-apply metadata

Export the 5 aggregate feature classes as shapefiles to M:\GIS\BytesProduction\Housing_Dev_DB\2022\22q4\shapefile
--Re-apply metadata (or remove geo-processing history)

AGO FC versions did not update on GISPROD.sde for all housing database files (Did not update). Published to AGO manually via ArcGIS Pro using 22q4 BytesProduction files.
