### ISSUE TITLE
Update: PLUTO minor

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/edm-overview#933]
Build PLUTO minor

**Comment by fvankrieken** [comment]
Tracked in this ticket https://github.com/NYCPlanning/db-pluto/issues/447 which of course cannot be interacted with because of archival of repo.

Should changes be needed, can make a new ticket in https://github.com/NYCPlanning/data-engineering

**Comment by damonmcc** [comment]
awaiting completion of EDM review

**Comment by damonmcc** [comment]
issue found during QAQC. from Lynn email:

Bldg class/land use

I can't figure out a reason why the values would change for the two records that Matt found. My concern is not that two records have changed values but that there could be a problem with the build process and the minor version isn't getting the same source files as the major version for non-DCP data sets.

Bldg class (2 records - 1 new null)
- 1005330030: V1 >> Q0
- 4004900050: Q0 >> Null

Land use (2 records - 1 new null)
- 1005330030: 11 >> 09
- 4004900050: 09 >> Null

**Comment by fvankrieken** [comment]
Doing a bit of an investigation into the above bbls

### 1 00533 0030
Looking at the pluto csv for the 23v1.2 and v1.1, it seems that the ordering of the districts for this bbl flipped
<img width="430" alt="image" src="https://github.com/NYCPlanning/edm-overview/assets/9454672/49f21dc3-1492-4657-a05d-67eeb9104057">

Need to look more specifically into the values - maybe this a lot that's currently falling 50/50 on a PARK and C1-7 district and is getting assigned non-deterministically?

Looking at this lot on [ZOLA](https://zola.planning.nyc.gov/l/lot/1/533/30?aerial-year=aerials-2016&layer-groups=%5B%22building-footprints%22%2C%22commercial-overlays%22%2C%22street-centerlines%22%2C%22subway%22%2C%22tax-lots%22%2C%22zoning-districts%22%5D&print=false&search=false&selectedCouncilDistricts=%5B%222013%22%5D&selectedFirm=%5B%22A%22%2C%22Shaded%20X%22%2C%22V%22%5D&selectedOverlays=%5B%22C1-1%22%2C%22C1-2%22%2C%22C1-3%22%2C%22C1-4%22%2C%22C1-5%22%2C%22C2-1%22%2C%22C2-2%22%2C%22C2-3%22%2C%22C2-4%22%2C%22C2-5%22%5D&selectedPfirm=%5B%22A%22%2C%22Shaded%20X%22%2C%22V%22%5D&selectedZoning=%5B%22BP%22%2C%22C1%22%2C%22C2%22%2C%22C3%22%2C%22C4%22%2C%22C5%22%2C%22C6%22%2C%22C7%22%2C%22C8%22%2C%22M1%22%2C%22M2%22%2C%22M3%22%2C%22PA%22%2C%22R1%22%2C%22R10%22%2C%22R2%22%2C%22R3%22%2C%22R4%22%2C%22R5%22%2C%22R6%22%2C%22R7%22%2C%22R8%22%2C%22R9%22%5D&shouldRefresh=false#17.38/40.727654/-73.995365), it seems like it really is a PARK - "Mercer Playground" specifically. 

<img width="1311" alt="image" src="https://github.com/NYCPlanning/edm-overview/assets/9454672/687a3f53-03af-4b94-9095-f0cafeab4042">

From this, it would seem that it should indeed be a park and that V1/11 (Park) is actually the correct bldgclass/landuse rather than Q0/09 (vacant lot)

### 4 00490 0050
This one has gone from PARK to R6
<img width="102" alt="image" src="https://github.com/NYCPlanning/edm-overview/assets/9454672/ffff38d4-edc3-47f3-924c-832c9a6fbfbd">

It's an odd little lot that's part of Hallets Point Playground in Queens ([ZOLA link](https://zola.planning.nyc.gov/l/lot/4/490/50?aerial-year=aerials-2016&layer-groups=%5B%22building-footprints%22%2C%22commercial-overlays%22%2C%22street-centerlines%22%2C%22subway%22%2C%22tax-lots%22%2C%22zoning-districts%22%5D&print=false&selectedCouncilDistricts=%5B%222013%22%5D&selectedFirm=%5B%22A%22%2C%22Shaded%20X%22%2C%22V%22%5D&selectedOverlays=%5B%22C1-1%22%2C%22C1-2%22%2C%22C1-3%22%2C%22C1-4%22%2C%22C1-5%22%2C%22C2-1%22%2C%22C2-2%22%2C%22C2-3%22%2C%22C2-4%22%2C%22C2-5%22%5D&selectedPfirm=%5B%22A%22%2C%22Shaded%20X%22%2C%22V%22%5D&selectedZoning=%5B%22BP%22%2C%22C1%22%2C%22C2%22%2C%22C3%22%2C%22C4%22%2C%22C5%22%2C%22C6%22%2C%22C7%22%2C%22C8%22%2C%22M1%22%2C%22M2%22%2C%22M3%22%2C%22PA%22%2C%22R1%22%2C%22R10%22%2C%22R2%22%2C%22R3%22%2C%22R4%22%2C%22R5%22%2C%22R6%22%2C%22R7%22%2C%22R8%22%2C%22R9%22%5D&shouldRefresh=false#17.93/40.774126/-73.936572))
<img width="1316" alt="image" src="https://github.com/NYCPlanning/edm-overview/assets/9454672/bed383df-4966-4f70-92f8-4f83eb947481">

Gonna look into this one. Really seems like it should be park and not null/vacant.

**Comment by damonmcc** [comment]
noting that above the Bldg class/land use issue wasn't the primary issue with this release:

> The issue is that the files are not in the location that the GIS needs them in in order to grab them and process them.
