### ISSUE TITLE
Run: M:/ Layer Inventory Script on Production 

### ISSUE THREAD

**Issue by caseysmithpgh** [NYCPlanning/edm-overview#954]
See #942 for build issue

TODO:
- [x] pull [repo](https://github.com/NYCPlanning/gis-m-data-inventory) into SCRIPTS production directory
- [x] copy ini file from DEV location
- [x] run on production layers

**Comment by jackrosacker** [comment]
Note: The total size of the M:\GIS\DATA folder is >250GB _but_ most of that size is contained within the 3D and Archive folders:
![image.png](https://images.zenhubusercontent.com/63c70f3233c7931e09b40a81/744a94a9-8fc1-47d2-a9c0-c94eb9315988)

We should be fine to copy all folders except those two to a test location in order to run the inventory script

**Comment by caseysmithpgh** [comment]
**Copy Repo to SCRIPTS directory:** 

1. Clone repo: ![image.png](https://images.zenhubusercontent.com/628cede5d6c2595e02af266c/96a3c917-7d04-41e4-a0f8-c1e442e20abb)
2. Copy ini from dev repo: ![image.png](https://images.zenhubusercontent.com/628cede5d6c2595e02af266c/60afaf26-f9c4-4bf1-92ed-54978574c62a)

**Next Steps:**
1. Copy data to temp testing location 
2. assign temp path to ini variable
3. run script
